version: "3.9"

services:
  mongo:
    build: database
    restart: always
    container_name: mongo
    command: ["mongod"]
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_HOST_PORT}:${MONGO_CONTAINER_PORT}